name: unified_eeg_benchmark
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - ld_impl_linux-64=2.40
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - typing_extensions=4.12.2
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==0.21.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - antropy==0.1.8
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - blobfile==3.0.0
      - bs4==0.0.2
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - coverage==7.6.10
      - cryptography==44.0.1
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - deepspeed==0.4.0
      - dill==0.3.9
      - diskcache==5.6.3
      - docopt==0.6.2
      - edfio==0.4.5
      - edflib-python==1.0.8
      - einops==0.7.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - h11==0.14.0
      - h5py==3.10.0
      - huggingface-hub==0.29.2
      - idna==3.10
      - imageio==2.36.1
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.31.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning==2.5.1
      - lightning-utilities==0.14.2
      - llvmlite==0.43.0
      - lxml==5.3.1
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - memory-profiler==0.61.0
      - mne==1.9.0
      - mne-bids==0.14
      - moabb==1.1.1
      - msal==1.31.1
      - multidict==6.2.0
      - mypy==1.15.0
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - office365-rest-python-client==2.5.14
      - openpyxl==3.1.5
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandarallel==1.6.5
      - pandas==2.2.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.48
      - propcache==0.3.0
      - protobuf==3.20.0
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pycryptodomex==3.21.0
      - pygments==2.19.1
      - pyhealth==1.1.4
      - pyjwt==2.10.1
      - pyparsing==3.2.1
      - pyriemann==0.6
      - pysocks==1.7.1
      - pytest==7.4.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.5.1
      - pytz==2024.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - rdkit==2024.9.5
      - regex==2024.11.6
      - requests==2.32.3
      - resampy==0.4.3
      - rfpimp==1.3.7
      - safetensors==0.5.3
      - scikit-image==0.25.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - seaborn==0.12.2
      - selenium==4.28.1
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - stochastic==0.7.0
      - tensorboardx==1.8
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - timm==0.4.12
      - tokenizers==0.15.2
      - tomli==2.2.1
      - torch==2.2.0
      - torchinfo==1.8.0
      - torchmetrics==1.7.0
      - tornado==6.4.2
      - tqdm==4.66.2
      - traitlets==5.14.3
      - transformers==4.38.1
      - trio==0.29.0
      - trio-websocket==0.11.1
      - triton==2.2.0
      - tzdata==2025.1
      - undetected-chromedriver==3.5.5
      - urllib3==1.26.15
      - wcwidth==0.2.13
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - websockets==14.2
      - wsproto==1.2.0
      - yarl==1.18.3
