name: unified_eeg_benchmark
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - antropy==0.1.8
      - asttokens==3.0.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - coverage==7.6.10
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - diskcache==5.6.3
      - docopt==0.6.2
      - edfio==0.4.5
      - edflib-python==1.0.8
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fonttools==4.55.3
      - h5py==3.12.1
      - idna==3.10
      - imageio==2.36.1
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.31.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - memory-profiler==0.61.0
      - mne==1.9.0
      - mne-bids==0.14
      - moabb==1.1.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.60.0
      - numpy==1.26.4
      - packaging==24.2
      - pandas==1.5.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.48
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pyriemann==0.6
      - pytest==7.4.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - requests==2.32.3
      - resampy==0.4.3
      - scikit-image==0.25.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.12.2
      - six==1.17.0
      - stack-data==0.6.3
      - stochastic==0.7.0
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - tomli==2.2.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - urllib3==1.26.20
      - wcwidth==0.2.13